CREATE TABLE [dbo].[Table]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [NUMERO_CONCURSO] VARCHAR(16) NOT NULL, 
    [DATA] DATETIME NOT NULL, 
    [ARRECADACAO_TOTAL] FLOAT NULL, 
    [ACUMULADO_DATA_ESPECIAL] FLOAT NOT NULL, 
    [PROXIMA_DATA] DATETIME NULL, 
    [VALOR_ACUMULADO] FLOAT NULL, 
    [ESTIMATIVA_PREMIO] FLOAT NULL
)
